// AUTO-GENERATED by scripts/build-apps-data.mjs (or Python equivalent on 2026-05-20).
// Do not edit by hand. Run: node scripts/build-apps-data.mjs

export interface AppData {
  slug: string;
  name: string;
  tagline: string;
  vertical: 'stem' | 'steam' | 'academics' | 'dir-fedc' | 'special-interest';
  heroColor: string;
  iconPath: string | null;
  mascotPath: string | null;
}

export const apps: AppData[] = [
  {
    "slug": "mindforge",
    "name": "MindForge",
    "tagline": "Trauma-informed social-emotional learning with gentle scaffolding.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/mindforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "wellnessforge",
    "name": "WellnessForge",
    "tagline": "Daily wellness habits \u2014 sleep, hydration, movement, mood.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/wellnessforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "creaturecare",
    "name": "CreatureCare",
    "tagline": "Tend a cast of digital creatures and learn empathy through care.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/creaturecare/icon.png",
    "mascotPath": null
  },
  {
    "slug": "equationquest",
    "name": "EquationQuest",
    "tagline": "Algebra mastery through visual proofs and stepped practice.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/equationquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "geometryforge",
    "name": "GeometryForge",
    "tagline": "Geometric reasoning with interactive constructions.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/geometryforge/icon.png",
    "mascotPath": "/apps/geometryforge/mascot.webp"
  },
  {
    "slug": "spectrumcanvas",
    "name": "SpectrumCanvas",
    "tagline": "Open-ended visual art with kid-safe color theory.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/spectrumcanvas/icon.png",
    "mascotPath": null
  },
  {
    "slug": "beatforge",
    "name": "BeatForge",
    "tagline": "Rhythm and music theory through pattern play.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/beatforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "readquest",
    "name": "ReadQuest",
    "tagline": "Reading comprehension built on cozy stories and recall games.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/readquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "grammarforge",
    "name": "GrammarForge",
    "tagline": "Grammar mastery through diagramming and pattern recognition.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/grammarforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "fossilforge",
    "name": "FossilForge",
    "tagline": "Paleontology field-work with real specimen taxonomies.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/fossilforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "wildlens",
    "name": "WildLens",
    "tagline": "Wildlife photography journal that teaches species ID.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/wildlens/icon.png",
    "mascotPath": null
  },
  {
    "slug": "mythforge",
    "name": "MythForge",
    "tagline": "World mythology comparative literacy \u2014 symbols, archetypes, tales.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/mythforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "focusforge",
    "name": "FocusForge",
    "tagline": "ADHD-friendly executive-function practice in 10-minute sessions.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/focusforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "soundsphere",
    "name": "SoundSphere",
    "tagline": "Sensory regulation through curated soundscapes.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/soundsphere/icon.png",
    "mascotPath": null
  },
  {
    "slug": "synaforge",
    "name": "SynaForge",
    "tagline": "Cross-sensory learning for neurodiverse minds.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/synaforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "proofquest",
    "name": "ProofQuest",
    "tagline": "Mathematical proofs as detective work.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/proofquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "waveforge",
    "name": "WaveForge",
    "tagline": "Acoustics and applied physics through hands-on signal play.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null
  },
  {
    "slug": "prismforge",
    "name": "PrismForge",
    "tagline": "Optics and color science via interactive light experiments.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null
  },
  {
    "slug": "harmonyforge",
    "name": "HarmonyForge",
    "tagline": "Music theory and concert performance prep.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/harmonyforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "dancequest",
    "name": "DanceQuest",
    "tagline": "Movement learning with choreographed sequence play.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/dancequest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "truthquest",
    "name": "TruthQuest",
    "tagline": "Critical thinking and media literacy through claim evaluation.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/truthquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "witquest",
    "name": "WitQuest",
    "tagline": "Wordplay, puns, and quick-wit puzzles.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/witquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "chronoquest",
    "name": "ChronoQuest",
    "tagline": "History time-travel adventure with primary-source craft.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/chronoquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "terravoyage",
    "name": "TerraVoyage",
    "tagline": "Geographic exploration with biome-based field studies.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/terravoyage/icon.png",
    "mascotPath": "/apps/terravoyage/mascot.webp"
  },
  {
    "slug": "bodyforge",
    "name": "BodyForge",
    "tagline": "Anatomy and body awareness with friendly clinical accuracy.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/bodyforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "activeforge",
    "name": "ActiveForge",
    "tagline": "Movement and fitness games designed for kid-bodies.",
    "vertical": "dir-fedc",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/activeforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "chemquest",
    "name": "ChemQuest",
    "tagline": "Chemistry lab with safe, age-appropriate experiments.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/chemquest/icon.png",
    "mascotPath": null
  },
  {
    "slug": "bioforge",
    "name": "BioForge",
    "tagline": "Biology field naturalism with curated taxonomies.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/bioforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "dataforge",
    "name": "DataForge",
    "tagline": "Data science \u2014 read, make, and reason about charts.",
    "vertical": "stem",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/dataforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "mangaforge",
    "name": "MangaForge",
    "tagline": "Manga storytelling and panel-craft for visual learners.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null
  },
  {
    "slug": "pixelforge",
    "name": "PixelForge",
    "tagline": "Pixel art creation with retro game-art conventions.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/pixelforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "craftforge",
    "name": "CraftForge",
    "tagline": "Hands-on crafts \u2014 thread, paper, simple electronics.",
    "vertical": "steam",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null
  },
  {
    "slug": "taleforge",
    "name": "TaleForge",
    "tagline": "Narrative writing with mythic-distance scaffolds.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/taleforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "newsforge",
    "name": "NewsForge",
    "tagline": "Kid-reporter media literacy \u2014 fact-finding, quotes, ethics.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/newsforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "cardforge",
    "name": "CardForge",
    "tagline": "Strategy card games designed for kids.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/cardforge/icon.png",
    "mascotPath": null
  },
  {
    "slug": "mapforge",
    "name": "MapForge",
    "tagline": "Cartography and spatial reasoning through map-making.",
    "vertical": "special-interest",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null
  }
];

export const appsBySlug: Record<string, AppData> = Object.fromEntries(
  apps.map(a => [a.slug, a])
);

export const verticalCounts = {
  "stem": 8,
  "steam": 7,
  "academics": 6,
  "dir-fedc": 7,
  "special-interest": 8
};
