// AUTO-GENERATED by scripts/build-apps-data.mjs (or Python equivalent).
// Do not edit by hand.

export interface AppData {
  slug: string;
  name: string;
  tagline: string;
  vertical: 'stem' | 'steam' | 'academics' | 'dir-fedc' | 'special-interest';
  heroColor: string;
  iconPath: string | null;
  mascotPath: string | null;
  implementing: boolean;
  standards: string[];
  hasM9Accessories: boolean;
  wave: number | null;
}

export const apps: AppData[] = [
  {
    "slug": "activeforge",
    "name": "ActiveForge",
    "tagline": "Build physical fitness, motor skills, and dance proficiency through camera-based movement tracking, choreography challenges, and sport skill progressions \u2014 aligning to both SHAPE America PE standards ",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/activeforge/icon.png",
    "mascotPath": "/apps/activeforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "adventurehub",
    "name": "AdventureHub",
    "tagline": "Cross-subject Hub app that aggregates contributions from 20+ portfolio source apps into 5 thematic adventure zones (Math Mountains, Word Woods, Science Labs, History Ruins, Creative Studio)",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "aiforge",
    "name": "AiForge",
    "tagline": "Learn how AI really works by building your own classifiers, training models, detecting bias, and navigating the ethics of a world run by algorithms \u2014 with an AI mentor that teaches you about itself.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/aiforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "beatforge",
    "name": "BeatForge",
    "tagline": "Music creation sandbox inside an RPG world where kids ages 10-14 build compositions using visual \"sound blocks\" that snap together on a sequencer canvas",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/beatforge/icon.png",
    "mascotPath": null,
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "bioforge",
    "name": "BioForge",
    "tagline": "Players learn anatomy and biomechanics through the lens of sports -- understanding how muscles generate force, how joints create leverage, how the cardiovascular system fuels performance, and how trai",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/bioforge/icon.png",
    "mascotPath": "/apps/bioforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "biomeforge",
    "name": "BiomeForge",
    "tagline": "Design aquariums, terrariums, and vivariums -- master ecology, food webs, and ecosystem balance at micro scale",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": "/apps/biomeforge/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "bodyforge",
    "name": "BodyForge",
    "tagline": "> Full body systems content has been merged into BioForge as part of portfolio restructuring.",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/bodyforge/icon.png",
    "mascotPath": "/apps/bodyforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "bridgeforge",
    "name": "BridgeForge",
    "tagline": "Project-based learning simulation with multi-week real-world challenges integrating math, science, social studies, and ELA",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/bridgeforge/icon.png",
    "mascotPath": "/apps/bridgeforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "cardforge",
    "name": "CardForge",
    "tagline": "Learn card games from basics to mastery, then amaze friends with step-by-step magic trick tutorials \u2014 a complete card skills academy with AI coaching for ages 9-14",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/cardforge/icon.png",
    "mascotPath": "/apps/cardforge/mascot.webp",
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "chanceforge",
    "name": "ChanceForge",
    "tagline": "Run a virtual casino, investigate insurance company math, predict sports outcomes, and solve medical diagnosis puzzles \u2014 mastering probability and statistics through real-world contexts where the math",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/chanceforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "chemquest",
    "name": "ChemQuest",
    "tagline": "Mix, react, and discover \u2014 a virtual chemistry lab where every reaction is an adventure and the periodic table is your map.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/chemquest/icon.png",
    "mascotPath": "/apps/chemquest/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "chronoquest",
    "name": "ChronoQuest",
    "tagline": "Players use a Chrono Device to visit historical eras, witness pivotal events firsthand, interact with historical figures, and complete missions that require understanding each era's culture, technolog",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/chronoquest/icon.png",
    "mascotPath": "/apps/chronoquest/mascot.webp",
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "cipherforge",
    "name": "CipherForge",
    "tagline": "Run a spy agency, learning cryptography from Caesar ciphers to RSA basics through narrative-driven missions \u2014 crack codes, build ciphers, compete in code-breaking duels, and escape timed puzzle rooms.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/cipherforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "circuitforge",
    "name": "CircuitForge",
    "tagline": "Build circuits on a virtual breadboard, watch electricity flow, code virtual robots, and learn the engineering behind every electronic device you use.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/circuitforge/icon.png",
    "mascotPath": "/apps/circuitforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "cityforge",
    "name": "CityForge",
    "tagline": "Players design buildings and plan cities that must satisfy structural physics, environmental constraints, and citizen needs",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/cityforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "civicforge",
    "name": "CivicForge",
    "tagline": "Players are newly elected to their town's Youth Council, making real decisions about budgets, zoning, public services, and community issues",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/civicforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "claimcraft",
    "name": "ClaimCraft",
    "tagline": "Visual argument mapping game where players build claim-evidence-reasoning chains and compete in debate duels",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/claimcraft/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "climatequest",
    "name": "ClimateQuest",
    "tagline": "Navigate a living Earth system where greenhouse gases, ocean currents, ice sheets, and ecosystems interconnect \u2014 make policy decisions and observe centuries of consequences through interactive climate",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/climatequest/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "coderealm",
    "name": "CodeRealm",
    "tagline": "Kids ages 10-14 program a companion robot using visual blocks that gradually \"peel back\" to reveal real Swift code as mastery increases",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/coderealm/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "cosmosforge",
    "name": "CosmosForge",
    "tagline": "Travel 13.8 billion years back to the Big Bang, watch the first stars ignite, witness galaxies collide, peer inside black holes, and hunt for exoplanets \u2014 an astrophysics odyssey through scales of spa",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/cosmosforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "craftforge",
    "name": "CraftForge",
    "tagline": "Virtual miniature painting and model-building that teaches color theory, brush techniques, and material science at micro scale",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": null,
    "mascotPath": "/apps/craftforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "creaturecare",
    "name": "CreatureCare",
    "tagline": "Players run an animal hospital, diagnosing and treating animals using real veterinary techniques",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/creaturecare/icon.png",
    "mascotPath": "/apps/creaturecare/mascot.webp",
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "cubesensei",
    "name": "CubeSensei",
    "tagline": "Learn the Rubik's Cube with a patient mentor and bite-sized practice.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/cubesensei/icon.png",
    "mascotPath": "/apps/cubesensei/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "curiosityquest",
    "name": "CuriosityQuest",
    "tagline": "A daily-question adventure that builds curiosity into habit.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": "/apps/curiosityquest/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "dancequest",
    "name": "DanceQuest",
    "tagline": "Dance as creative art: explore genres, compose choreography, analyze performances, and get camera-based movement feedback -- building artistic expression through dance composition and performance.",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/dancequest/icon.png",
    "mascotPath": "/apps/dancequest/mascot.webp",
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "dataforge",
    "name": "DataForge",
    "tagline": "Visual, block-based data science environment where players collect, clean, analyze, and visualize real-world datasets",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/dataforge/icon.png",
    "mascotPath": "/apps/dataforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "debateforge",
    "name": "DebateForge",
    "tagline": "Master the art of persuasion \u2014 research topics, construct arguments, deliver speeches, and compete in structured debates with AI opponents and real classmates.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/debateforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "depthquest",
    "name": "DepthQuest",
    "tagline": "Players pilot a research submarine through ocean zones (sunlight, twilight, midnight, abyssal, hadal), discovering marine species, studying coral reef health, mapping the ocean floor, and answering ma",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/depthquest/icon.png",
    "mascotPath": "/apps/depthquest/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "digquest",
    "name": "DigQuest",
    "tagline": "Excavate ancient sites layer by layer, analyze artifacts with real archaeological methods, and reconstruct the stories of lost civilizations \u2014 from Mesopotamia to the Maya.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/digquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "discretequest",
    "name": "DiscreteQuest",
    "tagline": "Exploration game teaching graph theory, combinatorics, and number theory through real-world mysteries",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/discretequest/icon.png",
    "mascotPath": "/apps/discretequest/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "earthforge",
    "name": "EarthForge",
    "tagline": "EarthForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "economicsforge",
    "name": "EconomicsForge",
    "tagline": "EconomicsForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "ecosphere",
    "name": "EcoSphere",
    "tagline": "Interactive climate and earth systems simulator where players manage interconnected ecosystems across geological time scales",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/ecosphere/icon.png",
    "mascotPath": "/apps/ecosphere/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "effectsforge",
    "name": "EffectsForge",
    "tagline": "Learn the science and art behind movie special effects \u2014 prosthetics chemistry, Foley sound physics, forced perspective optics, stop-motion animation, and lighting design \u2014 then produce your own short",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/effectsforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "engineerforge",
    "name": "EngineerForge",
    "tagline": "EngineerForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/engineerforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "ensemblequest",
    "name": "EnsembleQuest",
    "tagline": "Gamified cooperative creative projects that build social skills incrementally through a progressive social ladder: Solo, then Pair, then Group, then Perform",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/ensemblequest/icon.png",
    "mascotPath": "/apps/ensemblequest/mascot.webp",
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "equationquest",
    "name": "EquationQuest",
    "tagline": "Visual balance-scale approach to the entire CCSS EE domain",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/equationquest/icon.png",
    "mascotPath": "/apps/equationquest/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "escapeforge",
    "name": "EscapeForge",
    "tagline": "Single-player escape room iOS game for ages 9\u201314",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/escapeforge/icon.png",
    "mascotPath": "/apps/escapeforge/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "ethosforge",
    "name": "EthosForge",
    "tagline": "Navigate ethical dilemmas across science, technology, history, and daily life with an AI Socratic tutor",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/ethosforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "etymonrealm",
    "name": "EtymonRealm",
    "tagline": "Per `Docs/ANALYSIS_ETYMONREALM_VS_QUILLSPELL.md` (2026-05-19), EtymonRealm's Phase 1 scope overlapped near-totally with QuillSpell's existing morphology track:.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "farmquest",
    "name": "FarmQuest",
    "tagline": "Run a farm from soil to shelf \u2014 manage crops, raise animals, process food, market products, and balance sustainability with profitability across four seasons of scientific farming and agribusiness",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/farmquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "figureforge",
    "name": "FigureForge",
    "tagline": "Detective-style word puzzle game where students identify metaphors, similes, idioms, analogies, and personification through contextual investigation and creative writing challenges.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/figureforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "fitquest",
    "name": "FitQuest",
    "tagline": "A fitness RPG adventure where physical exercise (tracked via HealthKit) AND knowledge quiz performance jointly determine your character's progression",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/fitquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "flightforge",
    "name": "FlightForge",
    "tagline": "Design, build, and fly aircraft in a physics sandbox \u2014 master aerodynamics from paper planes to jet engines through the four forces of flight, wind tunnel experiments, and aviation engineering challen",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/flightforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "focusforge",
    "name": "FocusForge",
    "tagline": "A gamified executive function training adventure for students ages 9-14, with specific design for ADHD learners",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/focusforge/icon.png",
    "mascotPath": "/apps/focusforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "forgearena",
    "name": "Forgearena",
    "tagline": "A competitive multiplayer educational game where up to 30 students on any device battle in real-time quiz arenas, team challenges, and subject-specific tournaments \u2014 bridging iOS, Android, and web pla",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/forgearena/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "forgeclassroom",
    "name": "Forgeclassroom",
    "tagline": "A teacher-facing classroom management tool that works on any device \u2014 assign Forge app lessons, monitor student progress in real-time, generate standards-aligned reports, and run live quiz competition",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/forgeclassroom/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "forgeportal",
    "name": "Forgeportal",
    "tagline": "A cross-platform launcher and discovery hub for the entire Forge educational app portfolio \u2014 browse, download, and play any Forge app from one place on iOS, Android, Windows, or web, with unified prog",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/forgeportal/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "forgeworks",
    "name": "Forgeworks",
    "tagline": "> Engineering design features have been split across CircuitForge (electrical), MachineForge (mechanical), and MakerForge (maker/fabrication) as part of portfolio restructuring.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/forgeworks/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "fossilforge",
    "name": "FossilForge",
    "tagline": "Players run paleontology expeditions -- excavating fossil sites grid-by-grid, preparing specimens in the lab, classifying them taxonomically, and building museum exhibits",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/fossilforge/icon.png",
    "mascotPath": null,
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "fractionforge",
    "name": "FractionForge",
    "tagline": "Master fractions, decimals, and place value through virtual manipulatives, number line challenges, and real-world problem contexts \u2014 following the research-backed Concrete-Representational-Abstract in",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/fractionforge/icon.png",
    "mascotPath": "/apps/fractionforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "framequest",
    "name": "FrameQuest",
    "tagline": "Frame-by-frame animation creation that turns autistic preferences for precision and sequencing into creative storytelling",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/framequest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "functionforge",
    "name": "FunctionForge",
    "tagline": "Interactive function laboratory \u2014 input-output machines, function tables, linear/quadratic/exponential functions, and real-world data fitting",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/functionforge/icon.png",
    "mascotPath": "/apps/functionforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "geneforge",
    "name": "GeneForge",
    "tagline": "Extract DNA, map inheritance with Punnett squares, simulate CRISPR gene editing, and debate bioethics \u2014 explore genetics and biotechnology from Mendel's peas to modern gene therapy through hands-on vi",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/geneforge/icon.png",
    "mascotPath": "/apps/geneforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "geometryforge",
    "name": "GeometryForge",
    "tagline": "Interactive geometry exploration app for ages 9-14 covering the complete CCSS Geometry curriculum \u2014 transformations, coordinate geometry, similarity, proof, and 3D solids \u2014 using hands-on RealityKit 3",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/geometryforge/icon.png",
    "mascotPath": "/apps/geometryforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "grammarforge",
    "name": "GrammarForge",
    "tagline": "Master grammar, sentence structure, and language conventions through interactive sentence diagramming puzzles, error detective investigations, and style editing challenges \u2014 turning grammar rules into",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/grammarforge/icon.png",
    "mascotPath": "/apps/grammarforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "growforge",
    "name": "GrowForge",
    "tagline": "Grow a virtual garden powered by real weather data, design plant experiments, and discover the science of photosynthesis, genetics, and ecosystems \u2014 bridging the digital and natural worlds.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/growforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "harmonyforge",
    "name": "HarmonyForge",
    "tagline": "A music creation app that leverages autistic pattern-thinking strengths by translating visual patterns into music",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/harmonyforge/icon.png",
    "mascotPath": "/apps/harmonyforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "harvestforge",
    "name": "HarvestForge",
    "tagline": "Run a farm from seed to shelf \u2014 manage soil microbiomes, rotate crops, navigate drought and pest challenges, trace food through the supply chain, and investigate food justice issues that determine who",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/harvestforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "healthforge",
    "name": "HealthForge",
    "tagline": "HealthForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "heatforge",
    "name": "HeatForge",
    "tagline": "Race heat through solids, liquids, and gases \u2014 watch convection currents spiral, design insulation that defeats a blowtorch, and discover why ice cream melts faster on a hot sidewalk than in the freez",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/heatforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "historyforge",
    "name": "HistoryForge",
    "tagline": "HistoryForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": "/apps/historyforge/mascot.webp",
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "illusionforge",
    "name": "IllusionForge",
    "tagline": "Science-of-magic exploration app where kids discover the physics, chemistry, and cognitive psychology behind magic tricks and optical illusions",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "improvquest",
    "name": "ImprovQuest",
    "tagline": "Play improv comedy games with friends and AI scene partners \u2014 say \"yes, and...\" to adventure",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/improvquest/icon.png",
    "mascotPath": "/apps/improvquest/mascot.webp",
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "inclusionforge",
    "name": "InclusionForge",
    "tagline": "Experience daily life through different abilities, explore the history of disability rights, then design solutions that work for everyone \u2014 using Universal Design principles to build a more accessible",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/inclusionforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "inkquest",
    "name": "InkQuest",
    "tagline": "Junior investigative journalists at a school newspaper collect data, analyze patterns, identify bias, and write articles",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/inkquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "jestforge",
    "name": "JestForge",
    "tagline": "Learn to write jokes, riddles, and puns \u2014 then battle friends to see who's funniest",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/jestforge/icon.png",
    "mascotPath": "/apps/jestforge/mascot.webp",
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "labsmith",
    "name": "Labsmith",
    "tagline": "Virtual science lab where kids run real physics simulations \u2014 mix chemicals, build circuits, test buoyancy \u2014 earning mastery ranks through hands-on experimentation, not quizzes",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/labsmith/icon.png",
    "mascotPath": "/apps/labsmith/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "languageforge",
    "name": "LanguageForge",
    "tagline": "LanguageForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "levelforge",
    "name": "LevelForge",
    "tagline": "Players learn game design by designing, building, playtesting, and sharing their own playable games",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/levelforge/icon.png",
    "mascotPath": "/apps/levelforge/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "lifeforge",
    "name": "LifeForge",
    "tagline": "LifeForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "lifequest",
    "name": "LifeQuest",
    "tagline": "Navigate real-life consumer decisions \u2014 compare phone plans, read lease agreements, plan meals on a budget, spot consumer scams, and manage a household \u2014 through simulation of the everyday adult scena",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/lifequest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "linguaquest",
    "name": "LinguaQuest",
    "tagline": "Explore a vibrant adventure world where you MUST communicate in your target language to solve puzzles, make friends, order food, and save the kingdom \u2014 an RPG that makes language learning irresistible",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/linguaquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "logicquest",
    "name": "LogicQuest",
    "tagline": "Master the building blocks of clear thinking \u2014 identify logical fallacies, construct truth tables, map arguments, and crack syllogistic puzzles through detective investigations and debate challenges",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/logicquest/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "lorequest",
    "name": "LoreQuest",
    "tagline": "Kids ages 10-14 write branching stories inside an RPG world",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/lorequest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "machineforge",
    "name": "MachineForge",
    "tagline": "Build extreme machines from simple components \u2014 levers, pulleys, gears, and wheels \u2014 then test them in a physics sandbox, design vehicles, launch catapults, and demolish structures by exploiting mecha",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/machineforge/icon.png",
    "mascotPath": "/apps/machineforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "makerforge",
    "name": "MakerForge",
    "tagline": "Design, prototype, and virtually fabricate objects using 3D printing simulation, Arduino circuit building, and materials science \u2014 mastering the full engineering design process through constrained cha",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/makerforge/icon.png",
    "mascotPath": "/apps/makerforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "mangaforge",
    "name": "MangaForge",
    "tagline": "Create your own manga and anime-style comics -- learn art fundamentals, visual storytelling, and Japanese cultural literacy",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": null,
    "mascotPath": "/apps/mangaforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "mapforge",
    "name": "MapForge",
    "tagline": "Build fantasy worlds from tectonic plates up \u2014 master geography, ecology, economics, and storytelling through world-building",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": "/apps/mapforge/mascot.webp",
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "marketquest",
    "name": "MarketQuest",
    "tagline": "Virtual economy where students explore supply and demand, set prices, trade goods, and run market experiments -- building economic literacy through hands-on simulation and strategic decision-making.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/marketquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "mathlore",
    "name": "MathLore",
    "tagline": "Ethnomathematics adventure traveling through world civilizations \u2014 Babylonian base-60, Mayan vigesimal, Islamic geometric art, Indian zero/algebra, African fractal geometry, Inca quipu, Japanese origa",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/mathlore/icon.png",
    "mascotPath": "/apps/mathlore/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "mathquest",
    "name": "MathQuest",
    "tagline": "Master 12 math domains through interactive labs, SpriteKit-powered manipulatives, AI-driven tutoring, and cross-concept bridge challenges for ages 9\u201314.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/mathquest/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "measurequest",
    "name": "MeasureQuest",
    "tagline": "Hands-on measurement adventures: unit conversions, area and perimeter calculations, data representation, and real-world measurement applications -- building mathematical fluency through interactive ch",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/measurequest/icon.png",
    "mascotPath": "/apps/measurequest/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "mediaforge",
    "name": "MediaForge",
    "tagline": "MediaForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "medicquest",
    "name": "MedicQuest",
    "tagline": "Run a medical clinic, diagnose patients, perform first aid, and investigate disease outbreaks \u2014 learn anatomy, clinical reasoning, triage, and public health through case-based medical detective gamepl",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/medicquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "mindforge",
    "name": "MindForge",
    "tagline": "Adventure RPG where players navigate social scenarios, manage stress through mini-games, and build emotional intelligence by helping NPCs resolve conflicts",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/mindforge/icon.png",
    "mascotPath": "/apps/mindforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "mintforge",
    "name": "MintForge",
    "tagline": "Financial math game where financial scenarios ARE the math problems \u2014 compound interest, percentage markup, budgeting, loan amortization, stock market simulation",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/mintforge/icon.png",
    "mascotPath": "/apps/mintforge/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "mintquest",
    "name": "MintQuest",
    "tagline": "> Personal finance modules have been merged into VentureQuest as part of portfolio restructuring.",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/mintquest/icon.png",
    "mascotPath": "/apps/mintquest/mascot.webp",
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "mythforge",
    "name": "MythForge",
    "tagline": "Explore ancient civilizations through mythology-driven adventure quests \u2014 meet gods and heroes, battle mythological creatures, collect historical artifacts, and build ancient cities while learning Gre",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/mythforge/icon.png",
    "mascotPath": "/apps/mythforge/mascot.webp",
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "neuralquest",
    "name": "NeuralQuest",
    "tagline": "Players train image classifiers, build recommendation systems, discover how bias creeps into data, and explore AI ethics through hands-on experiments",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/neuralquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "newsforge",
    "name": "NewsForge",
    "tagline": "Run a digital newsroom \u2014 investigate stories through primary sources, evaluate credibility under deadline pressure, design data visualizations, produce multimedia reports, and compete to be first with",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/newsforge/icon.png",
    "mascotPath": "/apps/newsforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "nexusforge",
    "name": "NexusForge",
    "tagline": "Build and manage interconnected systems where actions cascade across ecology, economy, health, and policy",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/nexusforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "numberverse",
    "name": "Numberverse",
    "tagline": "Kids ages 10-14 construct and explore a living world using math",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/numberverse/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "originforge",
    "name": "OriginForge",
    "tagline": "Explore knowledge traditions from cultures worldwide \u2014 Indigenous ecological knowledge, African mathematical systems, Asian philosophical traditions, Pacific navigation techniques",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/originforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "physicsforge",
    "name": "PhysicsForge",
    "tagline": "PhysicsForge \u2014 a Spark & Anvil portfolio app.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/physicsforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "pixelforge",
    "name": "PixelForge",
    "tagline": "Gamified visual arts studio where players master design principles through creative challenges",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/pixelforge/icon.png",
    "mascotPath": "/apps/pixelforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "powerforge",
    "name": "PowerForge",
    "tagline": "Build power plants, manage electrical grids, and engineer renewable energy solutions \u2014 master energy conversion, thermodynamics, and sustainable engineering through infrastructure simulation and physi",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/powerforge/icon.png",
    "mascotPath": "/apps/powerforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "prismforge",
    "name": "PrismForge",
    "tagline": "Bend, split, and focus light through a virtual optics bench \u2014 explore lenses, prisms, mirrors, and the full electromagnetic spectrum while solving light-based engineering challenges and building devic",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/prismforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "proofquest",
    "name": "ProofQuest",
    "tagline": "Logic puzzle adventure building proof-readiness through deductive reasoning puzzles, informal proofs, and mathematical writing",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/proofquest/icon.png",
    "mascotPath": "/apps/proofquest/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "punchlineforge",
    "name": "PunchlineForge",
    "tagline": "> Meme studio and comic strip builder features have been merged into JestForge as part of portfolio restructuring.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/punchlineforge/icon.png",
    "mascotPath": "/apps/punchlineforge/mascot.webp",
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "questforge",
    "name": "QuestForge",
    "tagline": "Tabletop RPG creation toolkit where kids design characters (stat allocation = algebraic thinking), write quest narratives, build grid-based encounter maps (spatial reasoning), explore dice probability",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "quillspell",
    "name": "QuillSpell",
    "tagline": "Spelling and vocabulary mastery through pattern recognition and play.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": null,
    "mascotPath": "/apps/quillspell/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "ratiorealm",
    "name": "RatioRealm",
    "tagline": "Master ratios, proportions, and percentages through real-world simulation contexts \u2014 recipe scaling in kitchens, blueprint ratios in construction, and map scales in cartography \u2014 with visual models an",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/ratiorealm/icon.png",
    "mascotPath": "/apps/ratiorealm/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "readquest",
    "name": "ReadQuest",
    "tagline": "Build reading comprehension mastery through interactive passage analysis, evidence-based argument construction, and AI-generated comprehension challenges \u2014 with dual fiction and nonfiction tracks",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/readquest/icon.png",
    "mascotPath": null,
    "implementing": true,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "reelforge",
    "name": "ReelForge",
    "tagline": "Players learn filmmaking principles by creating short films within a virtual studio -- storyboarding scenes, choosing camera angles, directing lighting, designing sound, and editing on a timeline",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/reelforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "researchquest",
    "name": "ResearchQuest",
    "tagline": "Guided research adventure where students formulate questions, evaluate sources, synthesize findings, and produce reports -- building essential information literacy skills through structured research q",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/researchquest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "riddlerealm",
    "name": "RiddleRealm",
    "tagline": "Solve mind-bending riddles, craft your own brain teasers, and build a puzzle kingdom",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/riddlerealm/icon.png",
    "mascotPath": "/apps/riddlerealm/mascot.webp",
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "roboforge",
    "name": "RoboForge",
    "tagline": "Design robots from modular parts, program them in Swift-like block code, enter them in automated factory challenges, and compete in arena battles \u2014 mastering mechanical design, sensor programming, and",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/roboforge/icon.png",
    "mascotPath": "/apps/roboforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "safetyforge",
    "name": "SafetyForge",
    "tagline": "Navigate the digital world safely through interactive scenarios about privacy, cyberbullying, digital footprint, phishing detection, and responsible technology use \u2014 with a safe social media simulator",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/safetyforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "saffronlab",
    "name": "SaffronLab",
    "tagline": "Players travel the world to learn authentic recipes from different cultures, master cooking techniques through precision mini-games, and discover the science behind food \u2014 why bread rises, why onions ",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/saffronlab/icon.png",
    "mascotPath": "/apps/saffronlab/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "scienceforge",
    "name": "ScienceForge",
    "tagline": "Design real experiments, run virtual simulations, collect data, and build science fair presentations \u2014 with an AI mentor guiding every step of the scientific method.",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/scienceforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "sleuthlab",
    "name": "SleuthLab",
    "tagline": "Players run a detective agency, taking on mystery cases that require real forensic science techniques to solve",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/sleuthlab/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "soundsphere",
    "name": "SoundSphere",
    "tagline": "A soundscape creation tool that transforms heightened auditory sensitivity into a creative strength",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/soundsphere/icon.png",
    "mascotPath": "/apps/soundsphere/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "speakforge",
    "name": "SpeakForge",
    "tagline": "Speaking and listening skills platform for ages 10-14 covering presentations, discussions, debate, active listening, and media analysis",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/speakforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "spectrumcanvas",
    "name": "SpectrumCanvas",
    "tagline": "A digital art studio designed for autistic visual thinkers where every art material is simulated without the sensory challenges of the physical version",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/spectrumcanvas/icon.png",
    "mascotPath": "/apps/spectrumcanvas/mascot.webp",
    "implementing": true,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "stageforge",
    "name": "StageForge",
    "tagline": "Interactive theater arts studio where students write scripts, design sets, direct scenes, and perform -- building creative confidence through the dramatic arts",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/stageforge/icon.png",
    "mascotPath": "/apps/stageforge/mascot.webp",
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "starforge",
    "name": "StarForge",
    "tagline": "Players pilot spacecraft through the solar system and beyond, building and upgrading their ship, landing on planets to conduct experiments, establishing colonies, and answering astronomy challenges to",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/starforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "strategyforge",
    "name": "StrategyForge",
    "tagline": "Master chess, Go, checkers, backgammon, mancala, and Connect 4 through AI-coached lessons, puzzle challenges, and online play \u2014 with a unified strategy thinking curriculum for ages 9-14",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/strategyforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "styleforge",
    "name": "StyleForge",
    "tagline": "Players design garments from concept sketch through pattern-making, fabric selection, construction, and runway presentation",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": "/apps/styleforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "synaforge",
    "name": "SynaForge",
    "tagline": "A bidirectional creative tool where drawing produces music and music produces visual art -- simultaneously",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/synaforge/icon.png",
    "mascotPath": "/apps/synaforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "tableforge",
    "name": "TableForge",
    "tagline": "Master probability, strategy, and design thinking by creating physical board games",
    "vertical": "steam",
    "heroColor": "#E91E63",
    "iconPath": null,
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NCAS",
      "NGSS",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "taleforge",
    "name": "TaleForge",
    "tagline": "A multiplayer collaborative world-building and storytelling game where players co-create fantasy/sci-fi worlds in real-time using a tile-based map editor, then explore them as characters with AI-gener",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/taleforge/icon.png",
    "mascotPath": "/apps/taleforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 3
  },
  {
    "slug": "tectonicforge",
    "name": "TectonicForge",
    "tagline": "Pilot a drill into Earth's mantle, watch continents drift across 250 million years, trigger earthquakes and volcanic eruptions, and become a geological hazard engineer protecting cities from the dynam",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": "/apps/tectonicforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "terravoyage",
    "name": "TerraVoyage",
    "tagline": "Kids ages 10-14 traverse a stylized world map, identify locations through environmental and cultural clues, solve geography puzzles, and build a \"World Journal\" of discoveries",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/terravoyage/icon.png",
    "mascotPath": "/apps/terravoyage/mascot.webp",
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "terrawatch",
    "name": "Terrawatch",
    "tagline": "Gamified citizen science where players contribute real data to scientific databases (iNaturalist, Globe Observer) while earning XP and completing curriculum-aligned quests.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/terrawatch/icon.png",
    "mascotPath": "/apps/terrawatch/mascot.webp",
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": null
  },
  {
    "slug": "trailforge",
    "name": "TrailForge",
    "tagline": "Players are dropped into different wilderness biomes and must use real outdoor skills to survive and thrive",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/trailforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "truthquest",
    "name": "TruthQuest",
    "tagline": "Players are junior journalists at the Truth Tribune, investigating viral claims, social media posts, and news articles",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/truthquest/icon.png",
    "mascotPath": "/apps/truthquest/mascot.webp",
    "implementing": true,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "venturequest",
    "name": "VentureQuest",
    "tagline": "Players start and grow businesses from scratch -- beginning with a lemonade stand and progressing through food trucks, retail shops, tech startups, and enterprises",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/venturequest/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "waveforge",
    "name": "WaveForge",
    "tagline": "Visualize sound as a living waveform \u2014 tune an oscilloscope, build a speaker from scratch, engineer concert hall acoustics, decode whale songs, and master the physics of vibration that underlies all m",
    "vertical": "stem",
    "heroColor": "#29B6F6",
    "iconPath": null,
    "mascotPath": "/apps/waveforge/mascot.webp",
    "implementing": true,
    "standards": [
      "NGSS",
      "CCSS Math",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "weatherforge",
    "name": "WeatherForge",
    "tagline": "Build weather instruments, track real storms, predict tomorrow's weather, and simulate the forces behind Earth's most powerful phenomena.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/weatherforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  },
  {
    "slug": "wellnessforge",
    "name": "WellnessForge",
    "tagline": "Build health literacy through nutrition analysis, evidence-based substance abuse prevention, first aid simulations, and social-emotional learning \u2014 using the research-proven Life Skills Training model",
    "vertical": "dir-fedc",
    "heroColor": "#81C784",
    "iconPath": "/apps/wellnessforge/icon.png",
    "mascotPath": "/apps/wellnessforge/mascot.webp",
    "implementing": true,
    "standards": [
      "CASEL",
      "NGSS Health"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "wildlens",
    "name": "WildLens",
    "tagline": "Photograph real animals with your camera, identify species using on-device CoreML, and learn why they matter through food webs, habitat relationships, and ecosystem interconnections",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/wildlens/icon.png",
    "mascotPath": null,
    "implementing": true,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": true,
    "wave": 1
  },
  {
    "slug": "witquest",
    "name": "WitQuest",
    "tagline": "> Comedy RPG adventure mode has been merged into JestForge as part of portfolio restructuring.",
    "vertical": "academics",
    "heroColor": "#4A6FA5",
    "iconPath": "/apps/witquest/icon.png",
    "mascotPath": null,
    "implementing": true,
    "standards": [
      "CCSS ELA",
      "C3 Social Studies",
      "ISTE"
    ],
    "hasM9Accessories": true,
    "wave": 2
  },
  {
    "slug": "wonderforge",
    "name": "WonderForge",
    "tagline": "Become a science magician \u2014 watch \"impossible\" demonstrations, form hypotheses, reveal the physics and chemistry behind each trick, then perform your own science shows.",
    "vertical": "special-interest",
    "heroColor": "#FFA726",
    "iconPath": "/apps/wonderforge/icon.png",
    "mascotPath": null,
    "implementing": false,
    "standards": [
      "ISTE",
      "Common Sense Privacy"
    ],
    "hasM9Accessories": false,
    "wave": null
  }
];

export const appsBySlug: Record<string, AppData> = Object.fromEntries(
  apps.map(a => [a.slug, a])
);

export const verticalCounts = {
  "stem": 43,
  "steam": 18,
  "academics": 20,
  "dir-fedc": 14,
  "special-interest": 39
};
